apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  type: NodePort
  selector:
    app:  react
    replica:  blue
  ports:
    - nodePort: 32411
      protocol: TCP
      port: 3000
      targetPort: 3000
